### ISSUE TITLE
libguestfs 1.40.2 did not build - ocamlfind: Config file not found

### ISSUE THREAD

**Issue by jdandrea** [Amar1729/homebrew-formulae#4]
Tail end of build shows:

```
ocamlfind ocamlopt -g -annot -safe-string -warn-error CDEFLMPSUVYZX+52-3 -ccopt '-g -O2 -fno-strict-overflow -Wno-strict-overflow' -package str,unix -I . -c guestfs_config.ml -o guestfs_config.cmx
ocamlfind ocamlopt -g -annot -safe-string -warn-error CDEFLMPSUVYZX+52-3 -ccopt '-g -O2 -fno-strict-overflow -Wno-strict-overflow' -package str,unix -I . -c stringMap.ml -o stringMap.cmx
ocamlfind ocamlopt -g -annot -safe-string -warn-error CDEFLMPSUVYZX+52-3 -ccopt '-g -O2 -fno-strict-overflow -Wno-strict-overflow' -package str,unix -I . -c stringSet.ml -o stringSet.cmx
ocamlfind: Config file not found - neither /usr/local/etc/findlib.conf nor the directory /usr/local/etc/findlib.conf.d
make[2]: *** [guestfs_config.cmx] Error 2
make[2]: *** Waiting for unfinished jobs....
ocamlfind: Config file not found - neither /usr/local/etc/findlib.conf nor the directory /usr/local/etc/findlib.conf.d
make[2]: *** [stringMap.cmx] Error 2
ocamlfind: Config file not found - neither /usr/local/etc/findlib.conf nor the directory /usr/local/etc/findlib.conf.d
make[2]: *** [stringSet.cmx] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
**Formula**
Tap: amar1729/formulae
Path: /usr/local/Homebrew/Library/Taps/amar1729/homebrew-formulae/libguestfs.rb

**Configuration**
HOMEBREW_VERSION: 2.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 48a1637b24a0c329905a981f4cff547c7fa47943
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f62624705a55fc7233b9629081926146b2d6f416
Core tap last commit: 49 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.2-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: N/A

Other info available on request, if it would help. Will keep trying to track this down here as well.

Thank you!

**Comment by Amar1729** [comment]
Thanks for the report!

That's weird - I've built it (only on Mojave, which I'm running) and it seems to compile OK. Maybe ocaml-findlib has changed somehow on Cataline.

I will also say that v1.36 and v1.40 are still not completely working (maybe I should add caveats to them) - neither of them test properly on Mojave. Only the versioned v1.32 installs and tests properly for me.

Could you try:
```
brew install amar1729/formulae/libguestfs@1.32

brew test libguestfs@1.32
```

**Comment by Amar1729** [comment]
Edit: I've removed `libguestfs` v1.40 from master since it still doesn't build for me. If you'd like to help build it, I pushed a new branch, `wip-1.40.2`; otherwise, I'd recommend explicitly using the most recent version that works on osx, v1.32.

----

Aha - figured out the `ocamlfind` problem. For some reason, current homebrew-core `ocaml-findlib` does NOT install its config file when building from a bottle.

You can fix this by first running
```
brew install --build-from-source ocaml-findlib
```

And then:
```
brew install libguestfs
```

But you'll still run into the problem where libguestfs doesn't test properly. I don't know under which cases it will work or not work though.

**Comment by Amar1729** [comment]
See my separate tap for libguestfs: https://github.com/Amar1729/homebrew-libguestfs
