### ISSUE TITLE
3.0.7 doesn't work under Big Sur

### ISSUE THREAD

**Issue by avxkim** [Amar1729/homebrew-formulae#5]
Hello! Just wanted to let you know, that 3.0.7 version doesn't work with big sur. Or am i doing something wrong?

I'm trying to use it with a chrome extension called "Browserpass", when i open it - it says: "Error: Error: Specified native messaging host not found."

**Comment by Amar1729** [comment]
Did you make sure to run the `make` command specified by the caveats of this formula?

Should be something like:

```
$ PREFIX='/usr/local/opt/browserpass' make hosts-firefox-user -f /usr/local/opt/browserpass/lib/browserpass/Makefile
```

You can use `brew info browserpass` to show the full caveats.

**Comment by avxkim** [comment]
Yes, it was exactly this issue, thanks.
