### ISSUE TITLE
Cannot tap

### ISSUE THREAD

**Issue by chipsenkbeil** [Amar1729/homebrew-formulae#6]
Was trying to install browserpass for my Mac via `brew install amar1729/formulae/browserpass`, which both taps and installs the formula.

Unfortunately, it appears that homebrew fails with a syntax issue in a different formula as it's part of the tap, even though I don't (to my knowledge) use that formula at all. **libguestfs** seems to have a now-unsupported syntax. I remember getting warnings about this on a different M1 Mac I was setting up and now it seems to have switched to being an outright failure.

I'm assuming I'll be able to grab the formula that I want and add it to my own tap, but wanted to highlight this.

```
==> Tapping amar1729/formulae
Cloning into '/opt/homebrew/Library/Taps/amar1729/homebrew-formulae'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 331 (delta 4), reused 12 (delta 4), pack-reused 318
Receiving objects: 100% (331/331), 62.60 KiB | 1001.00 KiB/s, done.
Resolving deltas: 100% (181/181), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/amar1729/homebrew-formulae/libguestfs@1.32.rb
libguestfs@1.32: Calling depends_on :osxfuse is disabled! There is no replacement.
Please report this issue to the amar1729/formulae tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/amar1729/homebrew-formulae/libguestfs@1.32.rb:91

Error: Cannot tap amar1729/formulae: invalid syntax in tap!
```

**Comment by Amar1729** [comment]
Thanks for the report @chipsenkbeil ! I've removed `libguestfs@1.32` from this tap.
