### ISSUE TITLE
Compilation error of homebrew browserpass

### ISSUE THREAD

**Issue by GarciaManuel** [Amar1729/homebrew-formulae#8]
To fix it just move the variable version over the url var.

**Comment by Amar1729** [comment]
From what command are you seeing a compilation error? Homebrew style guidelines explicitly put `version` after the `url` attribute.

**Comment by Amar1729** [comment]
Closing this. Formula files are meant to be intaken by `brew`, not compiled directly. If you're seeing a compilation error, you're doing something wrong.
